services:
  jeanquin:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./id_jenkins.rsa:/run/secrets/jenkins_private:ro
  jeanquin_node1:
    image: jenkins/ssh-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAZke/LTWXyWIkRDcBziFWE0xL/HxW4EpPcqn24YubaRx8VpcI8Oc4DPLnn7/ekbjkr0TntOuHVQ7GjNGIKyKYYmi82i+NttrnVrO0ZZhVFzQthw/jYGLzppN/COf9LfLtC1iyE2/YjjyggkT0gB7W+QUIWa0yS3xyf0JBo6mx5RhABfr7JTcKZq6fD5/kOSXsrYAX5xVD7Q+pwoWr3FHuYeJzHDiTb54iorm9gaZsme/cCSCNV8t5USlhZI/AA5mdyWeTQBi6sIZbvunwB7Et29twvdQOgMxeh5rnHqLNXmDnvHNsR5EhVIG6Cf+AWl7XKNMGvzxHLtfHPbzVFX0xLethOz1wQMX/2/2DXPSkxVJ5r+QdLTNsp+fHiY/x+foNbtFDVmgMkDdpXzw8unHqHxE37nYiPtPrjCpA0a4lkZ0RqgUjdhLIh4nBDlxuAsxOluTYyOu24iUNALBG1t1bgSmratgAUfuUj6NfxdZiL0m7aUw+7vWF3jN+O1LA+VqvSv9kzfC7BXb5NtDpHLIFqLe98cXvtxzlC8rriy883kXj04jXUQASSqNUzMkRvEiUeSJ+jxqI7WsANyJW5PIBKwDRgETfoySM+KTGqfQ83XCVq+fvi3CTJJZgiu28VsowdKw0BtnGLHUyDYCocQsUSaqpY0z0aWJgmQO1T185lw== your_email@example.com
